### PR TITLE
Converted to use netstandard and dotnetcore supporting mongodb driver

### PR DESCRIPTION
**Pull request by mattwhetton**
Various changes to update AspNetCore.Identity.MongoDB to use the new MongoDb C# driver (pre).

Allows AspNetCore.Identity.MongoDB to run in asp.net core

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
Nice, I will have a look! Thanks a lot!

**Comment by tugberkugurlu** [comment]
@mattwhetton sorry for the delay getting back 😞 

This is pretty cool that you also used .NET Core version of the library. However, `2.3.0-beta1` has [dependency problems](https://github.com/mongodb/mongo-csharp-driver/pull/243#issuecomment-239518979) which have been fixed [here](https://github.com/mongodb/mongo-csharp-driver/commit/dd2b3219e42df1ef3936c212ce2e42c06bf8b265). I think we need to include the dependencies manually for now.

[I asked the team whether they plan to push the fix to NuGet](https://github.com/mongodb/mongo-csharp-driver/pull/243#issuecomment-241803205).

**Comment by tugberkugurlu** [comment]
@mattwhetton can you add the dependencies manually?

I will try to get build working on travis CI (which I did on https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/tree/rc2, I assume it will be probably getting it from there).

**Comment by mattwhetton** [comment]
I'll look at getting the dependencies mentioned sorted and get back to you

**Comment by mattwhetton** [comment]
I just added the collections dependency - are all the others required?

**Comment by tugberkugurlu** [comment]
@mattwhetton thanks a lot for the changes! 

It build locally nicely for me, I suppose that was only needed thing. I opened up #7 to make the build work which is on top of this. When that is merged, your changes will be on master and you will officially be the first contributor this project 🎉 🎉 👯 👯

**Comment by tugberkugurlu** [comment]
It's in now and I pushed a version to NuGet http://www.nuget.org/packages/AspNetCore.Identity.MongoDB/1.0.0-rc2

**Comment by mattwhetton** [comment]
No problem, glad to help.

**Pull request merged**
