### PR TITLE
Adding an IRoleStore and configuration helper so that it can be used with minimal changes from EntityFramework

### PR DESCRIPTION
**Pull request by runxc1**

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
@runxc1 thx for this!

I guess this has the changes from #5. If so, let's wait for that to be merged first, would that work @runxc1?

OTOH, I am not sure about having this 😞 Why don't you use claims to store Roles and need this instead?

**Comment by runxc1** [comment]
@tugberkugurlu waiting for changes from #5 is fine as this does contain that.   As for Roles, there is no reason not to provide an I RoleStore.  Roles and Claims both have their place.  Personally I prefer to program using claims but have the ability to assign claims to a role.  
All of that aside I found the VS new project template use the IRoleStore so implementing it made it easier to start a new project and swap out SqlServer for Mongo

**Comment by tugberkugurlu** [comment]
> have the ability to assign claims to a role.

The thing I am confused with is that [a role is a claim](https://github.com/dotnet/corefx/blob/v1.0.0/src/System.Security.Claims/src/System/Security/Claims/ClaimTypes.cs#L29) and I don't understand why Identity system has `IRoleStore`. There could be totally valid reasons for that but I haven't seen any 😞

**Comment by tugberkugurlu** [comment]
Seems like ASP.NET Core Identity 2 makes it easier to use the providers w/o roles. So, I will close this and still keep insisting on not implementing this 😄 Feel free to try to persuade me with reasons to implement it though!

**Pull request closed without merging**
