### PR TITLE
implement IQueryableUserStore<TUser>

### PR DESCRIPTION
**Pull request by hman-pro**
1. `NotSupportedException: Store does not implement IQueryableUserStore<TUser>`
In case when we want to query on users through Store (`UserManager`) and get information about users

2. auto-property accessor has conflict with `MongoIdentityUser `expansions by inheritance to new Model
in my scenario I have a model that inherit from `MongoIdentityUser `

```
public class User : MongoIdentityUser, IEntity
    {
        //public new string Id { get; set; }

        public User(string userName, string email) : base(userName, email)
        {

        }

        public User(string userName, AspNetCore.Identity.MongoDB.Models.MongoUserEmail email) : base(userName, email)
        {

        }

        public User(string userName) : base(userName)
        {

        }

        // Our Customs Fields
        public string NationalCode { get; set; }
       .
       .
}
```
I need to have public setter access to Id property.
_I didn't want to create a PR for two different subject but **GitHub** merge it._

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
> I need to have public setter access to Id property.

why?

**Comment by hman-pro** [comment]
In my case `IEntity` have `Id` property with public getter and setter (its standard in my framework)
Maybe I was wrong and should change `IEntity`.

**Comment by tugberkugurlu** [comment]
The changes here should be just around `MongoUserStore` and some tests for that.

**Comment by hman-pro** [comment]
@tugberkugurlu 
I've changed back `MongoUserStore`  , and try to solve my problem with parameterized constructors.

**Comment by tugberkugurlu** [comment]
Could you also add some tests around this?

**Comment by hman-pro** [comment]
@tugberkugurlu 
Of course.
I watched carefully you build test projects and infra for in place testing.
I love to complete testing project, I had busy days but I will work on testing in near future.
just like main AspNet/Identity test project.

**Comment by tugberkugurlu** [comment]
@SorenZ 👋 any updates on the tests for this to highlight what works and what does not?

**Comment by tugberkugurlu** [comment]
> @SorenZ 👋 any updates on the tests for this to highlight what works and what does not?

Hi @SorenZ 👋 I will close this for now as we are try to get this back up and this PR is a bit behind. Feel free to reopen, add tests and we can think about getting this working again 👍 /cc @dealproc

**Pull request closed without merging**
