### PR TITLE
 Implemented IUserAuthenticatorKeyStore and IUserTwoFactorRecoveryCode

### PR DESCRIPTION
**Pull request by tobieheyns**

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
@tcheyns sorry for jumping in late 😢 and huge thanks for this!

Build seems to be failing on Travis CI, any thoughts on why?

**Comment by tobieheyns** [comment]
Hi

I am not sure why its failing. Its compiling on my side, but let me do some investigation.

**Comment by tobieheyns** [comment]
Travis is failing on the tests implementation. When I run the tests on my machine, its trying to access the localhost instance of MongoDB.

**_"AspNetCore.Identity.MongoDB.Tests.dll" -nocolor -verbose -internaldiagnostics
  Discovering: AspNetCore.Identity.MongoDB.Tests
  Discovered:  AspNetCore.Identity.MongoDB.Tests
  Starting:    AspNetCore.Identity.MongoDB.Tests
  AspNetCore.Identity.MongoDB.Tests.MongoIdentityUserTests.MongoIdentityUser_CanBeSavedAndRetrieved_WhenItBecomesTheSubclass
    AspNetCore.Identity.MongoDB.Tests.MongoUserStoreTests.MongoUserStore_ShouldPutThingsIntoUsersCollectionByDefault
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself._

**Comment by tugberkugurlu** [comment]
@dealproc we can get this going once we fix https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/issues/55

**Comment by dealproc** [comment]
Maybe we need to think about setting up the build pipeline to execute with docker containers, if that is indeed possible?

**Comment by dealproc** [comment]
@tcheyns Can you implement the Token Storage (#45) into this pull request as well and provide tests?  According to me trying to do this, the interface includes three methods to be implemented, which you seem to have already (SetTokenAsync, RemoveTokenAsync, and GetTokenAsync).  This would complete the remainder of the work and we can close this PR as well as #45.

**Comment by dealproc** [comment]
@tcheyns I am going to consider that this PR is no longer valid as-is, and I am going to extract the work that you have done, along with the requests I made so we can get the functionality that #45 can be closed, and we can keep the functionality you've built with this PR.  I apologise for the delay in getting back to this, but other projects had to take priority.

**Comment by dealproc** [comment]
And I apologise.. I didn't thoroughly review the changes. It seems as if these changes were indeed in-place.

**Pull request merged**
